# For all options see https://github.com/bbatsov/rubocop/tree/master/config

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - Rakefile
  Exclude:
    - .*/**/*
    - vendor/**/*
    - bin/**/*
    - lib/companies-house.rb

# Limit lines to 80 characters.
Metrics/LineLength:
  Max: 90

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Lint/UnneededDisable:
  Severity: error

# Avoid methods longer than 30 lines of code
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 30

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: always

GlobalVars:
  AllowedVariables: [$statsd]

Style/NumericLiterals:
  MinDigits: 11

Metrics/ParameterLists:
  CountKeywordArgs: false

# Wants you to use the same argument names for every reduce. This seems kinda
# naff compared to naming them semantically
Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  EnforcedStyle: 'only_raise'

# Use trailing rather than leading dots on multi-line call chains
Layout/DotPosition:
  EnforcedStyle: trailing

# Allow non-ASCII characters (e.g. £) in comments
Style/AsciiComments:
  Enabled: false

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Style/FormatString:
  EnforcedStyle: sprintf

Style/Lambda:
  EnforcedStyle: literal

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Rails:
  Enabled: true

Rails/UniqBeforePluck:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
