version: 2

references:
  steps: &steps
    - checkout

    - type: cache-restore
      key: companies-house-rest-bundler-{{ checksum "companies-house-rest.gemspec" }}

    - run: gem install bundler -v 1.17

    - run: bundle install --path vendor/bundle

    - type: cache-save
      key: companies-house-rest-bundler-{{ checksum "companies-house-rest.gemspec" }}
      paths:
        - vendor/bundle

    - type: shell
      command: |
        bundle exec rspec --profile 10 \
                          --format RspecJunitFormatter \
                          --out /tmp/test-results/rspec.xml \
                          --format progress \
                          spec

    - type: store_test_results
      path: /tmp/test-results

    - run: bundle exec rubocop
jobs:
  build-ruby25:
    docker:
      - image: ruby:2.5
    steps: *steps
  build-ruby26:
    docker:
      - image: ruby:2.6
    steps: *steps
  build-ruby27:
    docker:
      - image: ruby:2.7
    steps: *steps

workflows:
  version: 2
  tests:
    jobs:
      - build-ruby25
      - build-ruby26
      - build-ruby27
